name: chess_llm
services:
  jupyter:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 8888:8888
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ..:/app
    env_file:
      - ../.env
    environment:
      - DISPLAY=host.docker.internal:0
    init: true
    entrypoint: sleep infinity
